name: tmsh_flutter
description: A new Flutter project.
version: 0.0.0+0

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  rxdart: ^0.24.1
  http: ^0.12.2
  kiwi: ^2.1.1
  redux: ^4.0.0+3
  flutter_redux: "^0.7.0"
  redux_logging: ^0.4.0
  built_value: ^7.1.0
  built_value_generator: ^7.1.0
  built_collection: ^4.2.2
  path_provider: ^1.4.0
  sembast: ^2.1.0+1
  bloc: ^6.1.0
  flutter_bloc: ^6.1.1

dependency_overrides:
  analyzer: 0.40.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_resolvers: ^1.4.2
  build_runner: ^1.10.6
  mockito: ^4.1.3



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
