name: tmsh_flutter
description: A new Flutter project.
version: 0.0.0+0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.2
  rxdart: ^0.27.0
  http: ^0.13.3
  kiwi: ^3.0.0-nullsafety.1
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  redux_logging: ^0.5.0
  built_value: ^8.0.6
  built_value_generator: ^8.0.6
  built_collection: ^5.0.0
  path_provider: ^2.0.1
  sembast: ^3.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  build_resolvers: ^2.0.2
  build_runner: ^2.0.3
  mockito: ^5.0.8

flutter:
  uses-material-design: true

  assets:
   - images/poster_placeholder.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
