name: tmsh_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^9.2.0
  built_collection: ^5.1.1
  built_value: ^8.12.4
  built_value_generator: ^8.12.4
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  flutter_redux: ^0.10.0
  http: ^1.6.0
  intl: ^0.20.2
  kiwi: ^5.0.1
  path_provider: ^2.1.5
  redux: ^5.0.0
  redux_logging: ^0.5.1
  rxdart: ^0.28.0
  sembast: ^3.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.12.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/poster_placeholder.png
